# Generated by Django 6.1.1 on 2026-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_age', models.IntegerField()),
                ('stu_class', models.CharField(max_length=20)),
                ('stu_email', models.EmailField(max_length=254)),
                ('stu_DOB', models.DateField()),
                ('stu_address', models.CharField(max_length=20)),
                ('stu_gender', models.CharField(max_length=20)),
                ('stu_grade', models.CharField(max_length=20)),
                ('stu_status', models.CharField(max_length=20)),
                ('stu_created_at', models.DateTimeField(auto_now_add=True)),
                ('stu_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
