# Generated by Django 6.1.1 on 2026-09-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('Finance', 'Finance'), ('Marketing', 'Marketing'), ('Sales', 'Sales'), ('Other', 'Other')], max_length=10)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
