# Generated by Django 6.1.1 on 2026-10-01 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('topic', models.CharField(choices=[('Technology', 'Technology'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Business', 'Business'), ('Health', 'Health'), ('Education', 'Education'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Politics', 'Politics'), ('Science', 'Science'), ('Art', 'Art'), ('Music', 'Music'), ('Photography', 'Photography'), ('Literature', 'Literature'), ('History', 'History'), ('Geography', 'Geography'), ('Mathematics', 'Mathematics'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Astronomy', 'Astronomy'), ('Geology', 'Geology'), ('Meteorology', 'Meteorology'), ('Oceanography', 'Oceanography'), ('Computer Science', 'Computer Science'), ('Data Science', 'Data Science'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Natural Language Processing', 'Natural Language Processing'), ('Computer Vision', 'Computer Vision'), ('Robotics', 'Robotics'), ('Internet of Things', 'Internet of Things'), ('Blockchain', 'Blockchain'), ('Cybersecurity', 'Cybersecurity'), ('Cloud Computing', 'Cloud Computing'), ('Big Data', 'Big Data'), ('Web Development', 'Web Development'), ('Mobile Development', 'Mobile Development'), ('Game Development', 'Game Development'), ('Software Engineering', 'Software Engineering'), ('Database Management', 'Database Management'), ('Network Security', 'Network Security'), ('System Administration', 'System Administration'), ('DevOps', 'DevOps'), ('Agile Methodologies', 'Agile Methodologies'), ('Scrum', 'Scrum'), ('Kanban', 'Kanban'), ('Lean Methodologies', 'Lean Methodologies'), ('Six Sigma', 'Six Sigma'), ('Kaizen', 'Kaizen'), ('Just In Time', 'Just In Time'), ('Lean Manufacturing', 'Lean Manufacturing'), ('Total Quality Management', 'Total Quality Management'), ('Quality Assurance', 'Quality Assurance'), ('Quality Control', 'Quality Control'), ('Risk Management', 'Risk Management'), ('Change Management', 'Change Management'), ('Project Management', 'Project Management'), ('Program Management', 'Program Management'), ('Portfolio Management', 'Portfolio Management'), ('Strategic Management', 'Strategic Management'), ('Business Analysis', 'Business Analysis'), ('Data Analysis', 'Data Analysis'), ('Business Intelligence', 'Business Intelligence'), ('Data Mining', 'Data Mining'), ('Data Visualization', 'Data Visualization'), ('Data Engineering', 'Data Engineering'), ('Data Architecture', 'Data Architecture'), ('Data Governance', 'Data Governance'), ('Data Quality', 'Data Quality'), ('Data Security', 'Data Security'), ('Data Privacy', 'Data Privacy'), ('Data Protection', 'Data Protection'), ('Data Management', 'Data Management'), ('Data Strategy', 'Data Strategy'), ('Data Operations', 'Data Operations'), ('Data Analytics', 'Data Analytics'), ('Data Science', 'Data Science')], max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.blog')),
            ],
        ),
    ]
